### ISSUE TITLE
DailyNotes Plugin - change date format

### ISSUE THREAD

**Issue by 1tecumseh** [akhater/akhater.github.io#1]
Hey,

is it possible to change the date format? I'm using DD.MM.YY and it is already changed in the TiddlyWiki options. But it seems to be not used by your plugin.

Thanks and keep up the good work!

**Comment by akhater** [comment]
Hello 1tecumseh 

yes I can do that, but it will probably not be in the next release

**Comment by akhater** [comment]
This is now done in version v0.0.30

https://github.com/akhater/Daily-Notes-for-TW5/releases
